# Stellar TOML Configuration for EasyA Stellar Wallet
# This file is required for MoneyGram Ramps integration (non-custodial wallet)

VERSION = "2.0.0"

# Network Passphrase (Testnet for now)
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

# Signing key for SEP-10 authentication (required for non-custodial wallet)
SIGNING_KEY = "GCDN4Z4S2JWANOEEYIXCAZSJKFFYYP3IVS2MJEYHXUBALFYTX6A5AXDX"

# SEP-10 Web Authentication Endpoint
WEB_AUTH_ENDPOINT = "https://easy-a-hack-stellar.vercel.app/api/sep10/auth"

# SEP-24 Transfer Server Endpoint
TRANSFER_SERVER_SEP0024 = "https://easy-a-hack-stellar.vercel.app/api/sep24"

# Organization Information
[DOCUMENTATION]
ORG_NAME = "EasyA Stellar Wallet"
ORG_URL = "https://github.com/lifafa03/EasyA-Hack_stellar"
ORG_DESCRIPTION = "Decentralized freelance platform built on Stellar blockchain with trustless escrow and fiat on/off-ramp capabilities"
ORG_OFFICIAL_EMAIL = "solipuram.rohanreddy@gmail.com"

# Supported Assets
[[CURRENCIES]]
code = "USDC"
issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
display_decimals = 2
name = "USD Coin (Testnet)"
desc = "USDC stablecoin for testnet"
is_asset_anchored = true
anchor_asset_type = "fiat"
anchor_asset = "USD"

[[CURRENCIES]]
code = "XLM"
issuer = "native"
display_decimals = 7
name = "Stellar Lumens"
desc = "Native Stellar asset"
is_asset_anchored = false

# Principal Contact
[[PRINCIPALS]]
name = "Rohan Solipuram"
email = "solipuram.rohanreddy@gmail.com"

# Validators (optional for wallet applications)
# [[VALIDATORS]]
# ALIAS = "easyastellar"
# DISPLAY_NAME = "EasyA Stellar Validator"
# PUBLIC_KEY = "YOUR_VALIDATOR_KEY_HERE"
